name: Teste Cobol GNU

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Cobol GNU
        run: sudo apt-get update && sudo apt-get install -y gnucobol4

      - name: Compilar programa
        run: cobc -x cartoes.cbl

      - name: Limpar arquivo de saída anterior
        run: rm -f relatorio.txt

      - name: Executar programa
        run: ./cartoes

      - name: Verificar saída
        run: cat relatorio.txt

      - name: Verificar versão do Cobol
        run: cobc --version
